#!/usr/bin/env bash
#confirming number of arguments
if [$# -lt 4]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#assigning parameters to varibales

path_to_file=$1
ip=$2
username=$3
path_to_shh_key=$4

#disabling strict host key checking

scp -o "StrictHostkeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

#checking if the file transfer was succesfull
if [$? -eq 0]
then
	echo "FILE WAS TRABSFERRED SUCCESSFULLY"
else
	echo "FILE NOT SUCCESSFULLY TRANSFERRED"
fi
