#!/usr/bin/env bash
#command to install nginx on web server


sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'


echo "Hello World!" | sudo tee /var/www/html/index.html


# testing nginx configurations
sudo nginx -t


sudo service nginx reload
