#!/usr/bin/env bash
#script that prints text 10 times with the while loop

COUNTER=0
while [ $COUNTER -lt 10 ]
do
	    if [ $COUNTER -eq 8 ]
		        then
				        echo "Best School"
					        echo "Hi"
						    else
							            echo "Best School"
								        fi
									    let COUNTER+=1
								    done
