#!/usr/bin/env bash
#using the while loop to print

ounter=1
message="Best School"


while [[ $counter -le 10 ]]; do

  echo "$message"

    if [[ $counter -eq 9 ]]; then
        echo "Hi"
	  fi

	    ((counter++))
	done
