#!/usr/bin/env bash
#Bash script that gives you information about the school file.
if [[ -s "school" ]]; then
echo "school file exists"
echo "school file is not empty"
echo "school is a regular file"

else
echo "school file does not exist"
fi
